---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flowers
  labels:
    purpose: flowers
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /home/titan/shared/tera/land/db/pv-flowers
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - titan
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
